# Generated by Django 3.2.15 on 2024-03-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Place',
        ),
    ]
