# Generated by Django 3.2.15 on 2024-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20240315_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'наличные'), ('CARD', 'карта')], db_index=True, default='CASH', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
